basic_font_path: webManager/static/font
basic_frame_path: webManager/static/images/image_frame
basic_image_path: webManager/static/images/shored_img
basic_port: 23433
basic_store_path: webManager/static/images/shored_img
chat_api_token: sk-SWLjAPztaxyu5dQnfhT2EyxFD4idjsqWVHUZ5MESTIGRVuis
chat_base_url: https://www.dmxapi.com/v1
chat_model: Doubao-1.5-lite-32k
image_selector_interval:
  days: 0
  hours: 0
  minutes: 3
module_dict:
  "AI\u4F5C\u8BCD": webManager.module.chatApi.ChatApi
  "\u5929\u6C14\u9884\u62A5": webManager.module.whetherReport.BaseWhetherReport
  "\u666E\u901A\u5C55\u793A_\u586B\u5145": webManager.module.imageReader.ImageReader
  "\u666E\u901A\u5C55\u793A_\u88C1\u526A": webManager.module.imageReaderCrop.ImageReaderCrop
  "\u7B80\u5355\u5929\u6C14": webManager.module.simpleWhetherReport.SimpleWhetherReport
module_used:
- "\u7B80\u5355\u5929\u6C14"
pre_content: "\u751F\u6D3B\u5982\u8346\u68D8\u4E1B\uFF0C\u523A\u75DB\u4E0D\u65AD\u3002\
  \u53EF\u522B\u7EDD\u671B\uFF0C\u5FC3\u5E95\u7684\u5E0C\u671B\u662F\u7834\u8327\u7684\
  \u529B\u91CF\u3002\u54EA\u6015\u6B64\u523B\u6DF1\u9677\u9ED1\u6697\uFF0C\u53EA\u8981\
  \u6000\u63E3\u90A3\u70B9\u5FAE\u5149\uFF0C\u7EC8\u80FD\u7A7F\u8D8A\u91CD\u91CD\u8270\
  \u96BE\uFF0C\u8FCE\u6765\u67F3\u6697\u82B1\u660E\uFF0C\u8BA9\u751F\u547D\u7EFD\u653E\
  \u51FA\u522B\u6837\u7684\u7EDA\u70C2\u5149\u5F69\u3002 "
target_img_size:
- 480
- 800
whether_api_token: f077afc158a17acaef193a6f67b0f5d3
whether_city: Shanghai,cn
