basic_font_path: webManager/static/font
basic_frame_path: webManager/static/images/image_frame
basic_image_path: webManager/static/images/shored_img
basic_port: 23433
basic_store_path: webManager/static/images/shored_img
chat_api_token: sk-SWLjAPztaxyu5dQnfhT2EyxFD4idjsqWVHUZ5MESTIGRVuis
chat_base_url: https://www.dmxapi.com/v1
chat_model: Doubao-1.5-lite-32k
image_selector_interval:
  days: 0
  hours: 0
  minutes: 1
module_used:
- webManager.module.imageReader.ImageReader
- webManager.module.whetherReport.BaseWhetherReport
- webManager.module.chatApi.ChatApi
pre_content: "\u7B49\u5F85\uFF0C\u5982\u6C99\u6F0F\u6EE4\u8FC7\u65F6\u5149\u3002\u604B\
  \u4EBA\u672A\u8D74\u7684\u7EA6\uFF0C\u4F3C\u60AC\u800C\u672A\u843D\u7684\u5251\u3002\
  \u53EF\u522B\u8BA9\u8FD9\u7B49\u5F85\u8680\u9AA8\u6210\u4F24\uFF0C\u52C7\u6562\u8F6C\
  \u8EAB\uFF0C\u4E5F\u8BB8\u65B0\u98CE\u666F\u5C31\u5728\u4E0B\u4E00\u5904\u3002\u522B\
  \u56F0\u5728\u539F\u5730\uFF0C\u5927\u80C6\u524D\u884C\uFF0C\u8BF4\u4E0D\u5B9A\u8F6C\
  \u89D2\u5C31\u4E0E\u66F4\u597D\u7684\u76F8\u9047\uFF0C\u628A\u7B49\u5F85\u7684\u714E\
  \u71AC\u5316\u4F5C\u6210\u957F\u7684\u517B\u5206\u3002 "
target_img_size:
- 800
- 480
whether_api_token: f077afc158a17acaef193a6f67b0f5d3
whether_city: Shanghai,cn
